In [241]:
import numpy as np
import pandas as pd
import datetime
from ast import literal_eval

In [242]:
file_path = r"C:\Users\sjung\Desktop\Data_Science_Lab\EDA_project\10th-EDA\Team_C\정제데이터\\"
drama_list_d = pd.read_csv(file_path+'1923_dramalist.csv', index_col=0, encoding='utf-8')
drama_list_d

,작품명,극본,연출,방송 기간,방송,방송사,유형,UHD,방송.1,시청,비고
0,"신비아파트 외전: 기억, 하리 2",이인혜,박용진,"2019.02.15, 2019.04.05",8,투니버스,금,NaN,NaN,(),1회 연장
1,너를 싫어하는 방법,"유소원, 정수현",오관진,"2019.04.1, 2019.04.2",2,"JTBC2,4","(월화), 단막",NaN,NaN,(),8회 연장
2,아름다운 세상,김지우,박찬홍,"2019.05.25, 2019.04.05",16,JTBC,금토,NaN,NaN,(),8회 연장
3,국민 여러분!,한정훈,김정현,"2019.05.28, 2019.04.01",36 (18),KBS2,월화,NaN,NaN,(),8회 연장
4,날 녹여주오,백미경,신우철,"2019.09.28, 2019.11.17",16,tvN,토일,NaN,NaN,(),사전제작
...,...,...,...,...,...,...,...,...,...,...,...
415,가슴이 뛴다,"정승주, 김하나","이민수, 이현석",2023.6.26,16,KBS2,월화,NaN,NaN,(),사전제작
416,기적의 형제,김지우,박찬홍,2023.6.28,16,JTBC,수목,NaN,NaN,(),사전제작
417,닥터 차정숙,정여랑,김대진,"2023.6.4, 2023.4.15",16,JTBC,토일,NaN,NaN,(),사전 제작
418,이로운 사기,한우주,이수현,"2023.7.18, 2023.5.29",16,tvN,월화,NaN,NaN,(),사전제작
419,행복배틀,주영아,김윤철,"2023.7.20, 2023.5.31",16,ENA,수목,NaN,NaN,(),사전제작

In [243]:
# meta_d = pd.read_csv(file_path+'meta_장르병합.csv', index_col=0, encoding='cp949')
meta_d = pd.read_csv(file_path+'meta_장르병합.csv', index_col=0,
                     encoding='cp949', converters={'출연자': literal_eval})
meta_d = meta_d.reset_index()
meta_d

,작품명,장르,방송사,전체회차,출연자,액션,코미디,드라마,스릴러,공포,판타지,가족,미스터리,전쟁,SF
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",1,"[신예은, 이나은, 신승호, 김동희 ]",0,0,1,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",1,"[박선호, 김소혜, 주우재 ]",0,0,1,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,1,"[이수경, 김진우, 진태현, 하연주, 이승연 ]",0,0,1,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,1,"[박신양, 고현정, 이민지, 변희봉 ]",0,0,1,1,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,1,"[여진구, 김상경, 이세영, 정혜영, 장광, 권해효 ]",0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,1,"[김명수, 최진혁, 최민수, 연우 ]",0,0,0,1,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,1,"[김태리, 오정세, 홍경]",0,0,0,1,0,1,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",1,"[박주미, 최명길, 김민준, 한다감, 전노민, 윤해영, 지영산, 유정후...",0,0,1,0,0,0,0,0,0,1
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,1,"[옥택연, 원지안, 박강현, 윤소희 ]",0,1,1,0,1,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,1,"[정우, 배현성, 박유림, 오만석, 이기우 ]",0,0,1,0,0,0,0,0,0,0

In [244]:
rating_d= pd.read_csv(file_path+'전체시청률.csv', encoding='utf-8')
rating_d

                      작품명        방송일자    시청률  방영연도  월   일  회차  연속방송
0     (아는 건 별로 없지만) 가족입니다  2020-06-01  3.122  2020  6   1   1     1
1     (아는 건 별로 없지만) 가족입니다  2020-06-02  3.930  2020  6   2   2     1
2     (아는 건 별로 없지만) 가족입니다  2020-06-08  3.345  2020  6   8   3     1
3     (아는 건 별로 없지만) 가족입니다  2020-06-09  3.862  2020  6   9   4     1
4     (아는 건 별로 없지만) 가족입니다  2020-06-15  3.188  2020  6  15   5     1
...                   ...         ...    ...   ... ..  ..  ..   ...
8594           힙합왕 - 나스나길  2019-08-16  1.200  2019  8  16   2     2
8595           힙합왕 - 나스나길  2019-08-23  1.300  2019  8  23   3     2
8596           힙합왕 - 나스나길  2019-08-30  1.350  2019  8  30   4     2
8597           힙합왕 - 나스나길  2019-09-06  0.600  2019  9   6   5     2
8598           힙합왕 - 나스나길  2019-09-13  0.750  2019  9  13   6     2

[8599 rows x 8 columns]

In [245]:
brand_d= pd.read_csv(file_path+'배우브랜드.csv', encoding='utf-8')
brand_d

        기간  순위  브랜드     참여지수    미디어지수     소통지수   커뮤니티지수  브랜드평판지수
0     1901   1  염정아  1372024  3513112  2794528  2282605  9962269
1     1901   2   현빈  2894066  2788296  1695680  2233463  9611504
2     1901   3  송혜교  1746374  2978220  3207168  1676911  9608673
3     1901   4  박보검  1933351  2855088  2242528  2345178  9376145
4     1901   5   유이   831162  3082884  3204288  1530746  8649080
...    ...  ..  ...      ...      ...      ...      ...      ...
1495  2306  46  이정진    61815    57143    79567   303056   501581
1496  2306  47  송하윤   146589   130888    87304   118397   483177
1497  2306  48  이원정   126062   115830   107849    80611   430352
1498  2306  49  최화정   116062   103990   159521    42884   422457
1499  2306  50  정우연   133603   123552    93420    71287   421863

[1500 rows x 8 columns]

## preprocessing
결측치 제거 및 rating_d의 방송일자 column을 datetime 형식으로 바꿈

In [246]:
# 결측치 제거
rating_d = rating_d.dropna(axis = 0).reset_index(drop=True)
rating_d.shape

(8550, 8)

In [247]:
# '방송일자'열의 dtype이 string으로 나오기 때문에, datetime으로 변환시키기
rating_d['방송일자'] = pd.to_datetime(rating_d['방송일자'])
print(rating_d.dtypes)

작품명             object
방송일자    datetime64[ns]
시청률            float64
방영연도             int64
월                int64
일                int64
회차               int64
연속방송             int64
dtype: object

In [248]:
# 12부작 ~ 16부작인 드라마만 추출

def drama_episode_extract(rating_d, min_episode, max_episode):
    #드라마별 회차 추출
    drama_episode_count = rating_d.groupby('작품명')['시청률'].count().reset_index()
    drama_episode_count.rename(columns={'시청률':'count'}, inplace = True)
    drama_episode_count.head()

    # min_episode이상, max_episode 미만의 드라마만 추출
    bool_mask = (min_episode<=drama_episode_count['count']) & (drama_episode_count['count']<=max_episode)
    extracted_dama_df = drama_episode_count[bool_mask].reset_index(drop=True)
    
    extracted_dama_ratig = rating_d[rating_d['작품명'].isin(extracted_dama_df['작품명'])].reset_index(drop=True)
    extracted_dama_ratig
    
    return extracted_dama_ratig


min_episode = 12
max_episode = 16
extracted_dama_ratig = drama_episode_extract(rating_d, min_episode, max_episode)
extracted_dama_ratig

                      작품명       방송일자    시청률  방영연도   월   일  회차  연속방송
0     (아는 건 별로 없지만) 가족입니다 2020-06-01  3.122  2020   6   1   1     1
1     (아는 건 별로 없지만) 가족입니다 2020-06-02  3.930  2020   6   2   2     1
2     (아는 건 별로 없지만) 가족입니다 2020-06-08  3.345  2020   6   8   3     1
3     (아는 건 별로 없지만) 가족입니다 2020-06-09  3.862  2020   6   9   4     1
4     (아는 건 별로 없지만) 가족입니다 2020-06-15  3.188  2020   6  15   5     1
...                   ...        ...    ...   ...  ..  ..  ..   ...
3646                 황금정원 2019-09-28  8.250  2019   9  28  11     4
3647                 황금정원 2019-10-05  8.850  2019  10   5  12     4
3648                 황금정원 2019-10-12  9.075  2019  10  12  13     4
3649                 황금정원 2019-10-19  8.600  2019  10  19  14     4
3650                 황금정원 2019-10-26  7.050  2019  10  26  15     4

[3651 rows x 8 columns]

## 시청률 top 10 드라마 추출

In [249]:
# 드라마별 평균 시청률 계산
mean_rating_df = extracted_dama_ratig.groupby("작품명")['시청률'].mean().reset_index()
# 시청률 높은 순서대로 정렬
mean_rating_df = mean_rating_df.sort_values(by='시청률', ascending = False)
mean_rating_df

            작품명        시청률
224     펜트하우스 2  22.158974
47   낭만닥터 김사부 2  18.311458
194    재벌집 막내아들  17.398500
225     펜트하우스 3  17.230952
48   낭만닥터 김사부 3  13.725000
..          ...        ...
185       이미테이션   0.929167
61      달리는 조사관   0.912000
232       한 사람만   0.902000
106     보라! 데보라   0.881071
154        야식남녀   0.775167

[241 rows x 2 columns]

In [234]:
# 시청률 top10 드라마 추출

top_number = 10 # 상위 몇 개까지 추출할지 결정

top_n_drama_df = mean_rating_df.iloc[:top_number,:].reset_index(drop=True)
top_n_drama_df

          작품명        시청률
0     펜트하우스 2  22.158974
1  낭만닥터 김사부 2  18.311458
2    재벌집 막내아들  17.398500
3     펜트하우스 3  17.230952
4      부부의 세계  17.192556
5       펜트하우스  16.409091
6        열혈사제  16.115000
7  낭만닥터 김사부 3  13.725000
8      닥터 차정숙  13.682750
9      원 더 우먼  13.543750

In [250]:
# 드라마별 방송 기간 추출
def attach_drama_broadcasting_period(top_n_drama_df, drama_list_d):
    top_n_drama_df['시작'] = datetime.date(year=2000, month=1, day=1)
    top_n_drama_df['종영'] = datetime.date(year=2000, month=1, day=1)

    for i, title in enumerate(top_n_drama_df['작품명']):
        drama = drama_list_d[drama_list_d['작품명'] == title]
        begin, end = drama['방송 기간'].values[0].split(',')
        top_n_drama_df.loc[i,'시작'] =\
                        datetime.datetime.strptime(begin.strip(), '%Y.%m.%d').date()
        top_n_drama_df.loc[i,'종영'] =\
                        datetime.datetime.strptime(end.strip(), '%Y.%m.%d').date()
    return top_n_drama_df
    
    
top_n_drama_df = attach_drama_broadcasting_period(top_n_drama_df, drama_list_d)
top_n_drama_df

,작품명,시청률,시작,종영,출연자
0,펜트하우스 2,22.158974,2021-02-19,2021-04-02,"[유진, 김소연, 이지아 ]"
1,낭만닥터 김사부 2,18.311458,2020-02-25,2020-01-06,"[한석규, 안효섭, 이성경, 김주헌 ]"
2,재벌집 막내아들,17.398500,2022-12-25,2022-11-18,"[송중기, 이성민, 박혁권, 김남희, 윤제문, 박지현 ]"
3,펜트하우스 3,17.230952,2021-06-04,2021-09-10,"[유진, 김소연, 이지아 ]"
4,부부의 세계,17.192556,2020-03-27,2020-05-16,"[김희애, 박해준, 한소희, 박선영, 김영민 ]"
5,펜트하우스,16.409091,2021-01-05,2020-10-26,"[이지아, 김소연, 유진 ]"
6,열혈사제,16.115000,2019-04-20,2019-02-15,"[김남길, 김성균, 이하늬, 고준, 금새록 ]"
7,낭만닥터 김사부 3,13.725000,2023-06-17,2023-04-28,"[한석규, 안효섭, 이성경, 김주헌 ]"
8,닥터 차정숙,13.682750,2023-06-04,2023-04-15,"[엄정화, 김병철, 민우혁, 명세빈]"
9,원 더 우먼,13.543750,2021-11-06,2021-09-17,"[이하늬, 이상윤, 진서연, 이원근 ]"

In [251]:
# 시작일과 종영일이 바뀐 경우, 원래대로 바꿔주기
def swap_wrong_date(top_n_drama_df: pd.DataFrame)->pd.DataFrame:
    # 시작일이 종영일보다 뒤인 경우(즉, 둘이 바뀌어서 잘못 추출된 경우) 추출
    bool_mask = top_n_drama_df['시작'] > top_n_drama_df['종영']
    # 원래 '시작', '종영' 순서로 열이 되어 있지만 추후에 둘을 바꾸기 위해 순서 바꿔서 추출
    end_start_date =  top_n_drama_df[bool_mask][['종영', '시작']]
    top_n_drama_df.loc[bool_mask, ['시작','종영']] = end_start_date.values
    return top_n_drama_df


top_n_drama_df = swap_wrong_date(top_n_drama_df)
top_n_drama_df

,작품명,시청률,시작,종영,출연자
0,펜트하우스 2,22.158974,2021-02-19,2021-04-02,"[유진, 김소연, 이지아 ]"
1,낭만닥터 김사부 2,18.311458,2020-01-06,2020-02-25,"[한석규, 안효섭, 이성경, 김주헌 ]"
2,재벌집 막내아들,17.398500,2022-11-18,2022-12-25,"[송중기, 이성민, 박혁권, 김남희, 윤제문, 박지현 ]"
3,펜트하우스 3,17.230952,2021-06-04,2021-09-10,"[유진, 김소연, 이지아 ]"
4,부부의 세계,17.192556,2020-03-27,2020-05-16,"[김희애, 박해준, 한소희, 박선영, 김영민 ]"
5,펜트하우스,16.409091,2020-10-26,2021-01-05,"[이지아, 김소연, 유진 ]"
6,열혈사제,16.115000,2019-02-15,2019-04-20,"[김남길, 김성균, 이하늬, 고준, 금새록 ]"
7,낭만닥터 김사부 3,13.725000,2023-04-28,2023-06-17,"[한석규, 안효섭, 이성경, 김주헌 ]"
8,닥터 차정숙,13.682750,2023-04-15,2023-06-04,"[엄정화, 김병철, 민우혁, 명세빈]"
9,원 더 우먼,13.543750,2021-09-17,2021-11-06,"[이하늬, 이상윤, 진서연, 이원근 ]"

## 드라마별 출연자 데이터 만들기

In [252]:
# top_n_drama_df에 '출연자' 열을 추가
def add_actor_column(top_n_drama_df:pd.DataFrame, meta_df:pd.DataFrame)->pd.DataFrame:
    actor_col = []
    for title in top_n_drama_df['작품명']:
        meta_df = meta_d[['작품명','출연자']]
        actors = meta_df[meta_df['작품명'] == title]['출연자'].values[0]
        actor_col.append(actors)

    top_n_drama_df['출연자'] = pd.Series(actor_col)
    return top_n_drama_df


top_n_drama_df = add_actor_column(top_n_drama_df, meta_d)
top_n_drama_df

,작품명,시청률,시작,종영,출연자
0,펜트하우스 2,22.158974,2021-02-19,2021-04-02,"[유진, 김소연, 이지아 ]"
1,낭만닥터 김사부 2,18.311458,2020-01-06,2020-02-25,"[한석규, 안효섭, 이성경, 김주헌 ]"
2,재벌집 막내아들,17.398500,2022-11-18,2022-12-25,"[송중기, 이성민, 박혁권, 김남희, 윤제문, 박지현 ]"
3,펜트하우스 3,17.230952,2021-06-04,2021-09-10,"[유진, 김소연, 이지아 ]"
4,부부의 세계,17.192556,2020-03-27,2020-05-16,"[김희애, 박해준, 한소희, 박선영, 김영민 ]"
5,펜트하우스,16.409091,2020-10-26,2021-01-05,"[이지아, 김소연, 유진 ]"
6,열혈사제,16.115000,2019-02-15,2019-04-20,"[김남길, 김성균, 이하늬, 고준, 금새록 ]"
7,낭만닥터 김사부 3,13.725000,2023-04-28,2023-06-17,"[한석규, 안효섭, 이성경, 김주헌 ]"
8,닥터 차정숙,13.682750,2023-04-15,2023-06-04,"[엄정화, 김병철, 민우혁, 명세빈]"
9,원 더 우먼,13.543750,2021-09-17,2021-11-06,"[이하늬, 이상윤, 진서연, 이원근 ]"

## 드라마 시작과 종영 때의 출연자의 브랜드 평판 구하기
아직 다 못함

문제점: 브랜드 평판이 모든 달에 다 구해진 게 아니다....

In [202]:
a = top_n_drama_df['시작'].astype(str)[0]

a[2:4]

'21'

In [255]:
for actor in top_n_drama_df['출연자'][2]:
    print(brand_d[brand_d['브랜드'] == actor.strip()])

        기간  순위  브랜드     참여지수    미디어지수     소통지수   커뮤니티지수  브랜드평판지수
76    1906  27  송중기  1282091   439941   382665   587536  2692233
551   2102   2  송중기  2263193  1493959   840478   526334  5123964
600   2104   1  송중기  2005678  2212952  2555897  2056232  8830758
1200  2212   1  송중기  1435777  1294851  1316192  3743334  7790154
1251  2301   2  송중기  2564861  1512352  1945979  1982317  8005509
        기간  순위  브랜드    참여지수   미디어지수     소통지수   커뮤니티지수  브랜드평판지수
279   2002  30  이성민  224531  580356   174240   315471  1294598
1205  2212   6  이성민  475418  412741   546521  1136643  2571323
1256  2301   7  이성민  623809  536164  1073798  1162312  3396083
Empty DataFrame
Columns: [기간, 순위, 브랜드, 참여지수, 미디어지수, 소통지수, 커뮤니티지수, 브랜드평판지수]
Index: []
        기간  순위  브랜드    참여지수   미디어지수    소통지수  커뮤니티지수  브랜드평판지수
1436  2305  37  김남희  177735  161132  186342  141066   666275
1479  2306  30  김남희  159073  144788  203289  250928   758078
        기간  순위  브랜드    참여지수   미디어지수    소통지수  커뮤니티지수  브랜드평판지수
1238  2212  39  윤제문  132046  119176  201024  132178   584424
1292  2301  43  윤제문  125354  110811  389454  228146   853764
       기간  순위  브랜드    참여지수    미디어지수    소통지수  커뮤니티지수  브랜드평판지수
131  1908  32  박지현  132493  1016652  620064  315732  2084941
458  2009  30  박지현  700219   578004  194112  123482  1595817
459  2009  30  박지현  700219   578004  194112  123482  1595817
785  2110  36  박지현  322522   207998  184444  157627   872591

In [254]:
for actor in top_n_drama_df['출연자'][1]:
    print(brand_d[brand_d['브랜드'] == actor.strip()])

        기간  순위  브랜드    참여지수    미디어지수     소통지수  커뮤니티지수  브랜드평판지수
137   1908  38  한석규  190752  1036056   341280  347044  1915132
206   2001   7  한석규  593517  1836912   379872  522952  3333253
264   2002  15  한석규  654915  1407672   434016  484123  2980726
1346  2303  47  한석규  105096    95624   242031   45769   488520
1374  2304  25  한석규   73604    65122   236026  394570   769322
1403  2305   4  한석규  210038   194337  1247293  753615  2405283
1454  2306   5  한석규  475032   441570  1205115  770594  2892310
        기간  순위  브랜드     참여지수    미디어지수     소통지수  커뮤니티지수  브랜드평판지수
81    1906  32  안효섭   909251  1090152   222336  289585  2511324
202   2001   3  안효섭  3511029  1638756   323424  461963  5935172
256   2002   7  안효섭  2607143  1428252   447840  467192  4950427
708   2109   9  안효섭  1076704   744335   635509  863553  3320101
757   2110   8  안효섭   900257   729542   623286  934909  3187993
1402  2305   3  안효섭   372329   341827  1409471  428235  2551863
1452  2306   3  안효섭   730630   672844   904094  802243  3109810
        기간  순위  브랜드     참여지수    미디어지수    소통지수  커뮤니티지수  브랜드평판지수
204   2001   5  이성경  1212467  1660512  378432  724942  3976354
260   2002  11  이성경  1527407  1234800  504000  377702  3643909
974   2205  25  이성경   241956   240224  224361  427553  1134094
1017  2206  18  이성경   204504   265783  303246  496782  1270315
1409  2305  10  이성경   292020   260489  997356  389804  1939668
1459  2306  10  이성경   382883   352638  747542  541952  2025015
        기간  순위  브랜드    참여지수    미디어지수    소통지수  커뮤니티지수  브랜드평판지수
221   2001  22  김주헌  242613  1126020  139968  258534  1767135
269   2002  20  김주헌  707372   953736  189216  189243  2039567
398   2008  49  김주헌  275200   192864  139104   41640   648808
549   2011  50  김주헌  232082   438333  167837  309688  1147939
839   2112  40  김주헌  122934   198104  172373  119669   613080
874   2201  25  김주헌  293050   307205  264231  191767  1056254
1116  2209  17  김주헌  270656   256064  291762  428328  1246810

In [263]:
brand_d['기간'].head()

0    1901
1    1901
2    1901
3    1901
4    1901
Name: 기간, dtype: int64

In [264]:
top_n_drama_df['시작'].to_string

<bound method Series.to_string of 0    2022-03-27
1    2020-03-28
2    2020-09-19
3    2019-09-22
4    2021-03-13
5    2022-04-02
6    2019-09-28
7    2021-02-19
8    2022-09-24
9    2020-10-09
Name: 시작, dtype: object>