In [9]:
import numpy as np
import pandas as pd

In [10]:
file_path = r"C:\Users\sjung\Desktop\Data_Science_Lab\EDA_project\10th-EDA\Team_C\정제데이터\\"
meta= pd.read_csv(file_path+'메타_전처리1.csv')
meta.head()

,작품명,장르,방송사,전체회차,출연자,시작일,종료일,요일,월,화,...,한예리,한지민,한지현,한지혜,한채영,한효주,함은정,현빈,황민현,황정음
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",2018-07-01 0:00,2018-09-16 0:00,수일,0,0,...,0,0,0,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']",2019-01-02 0:00,2019-02-07 0:00,수목,0,0,...,0,0,0,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",2019-01-02 0:00,2019-05-31 0:00,월화수목금,1,1,...,0,0,0,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",2019-01-07 0:00,2019-03-26 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",2019-01-07 0:00,2019-03-04 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0

In [11]:
meta.columns

Index(['작품명', '장르', '방송사', '전체회차', '출연자', '시작일', '종료일', '요일', '월', '화',
       ...
       '한예리', '한지민', '한지현', '한지혜', '한채영', '한효주', '함은정', '현빈', '황민현', '황정음'],
      dtype='object', length=1327)

In [20]:
meta.head(1)

,작품명,장르,방송사,전체회차,출연자,시작일,종료일,요일,월,화,...,판타지 사극,판타지 액션 로맨스,프라이빗 오피스 멜로,하드보일드,학원물 로맨스,현대 판타지,회사 드라마,휴머니즘,휴먼,휴먼 판타지 드라마
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",2018-07-01 0:00,2018-09-16 0:00,수일,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# meta에서 뒤쪽에 있는 배우 칼럼 삭제
meta = meta.drop(meta.columns[166:], axis=1)

# 작품명과 장르 칼럼들만 남기고 나머지 다 삭제
genre_start_index = meta.columns.to_list().index(' SF')
extracted_meta = pd.concat((meta['작품명'], meta.iloc[:,genre_start_index:]), axis = 1)
extracted_meta

,작품명,SF,가족,감성,격정멜로,공포,교육,군대,낭만,논픽션,...,판타지 사극,판타지 액션 로맨스,프라이빗 오피스 멜로,하드보일드,학원물 로맨스,현대 판타지,회사 드라마,휴머니즘,휴먼,휴먼 판타지 드라마
0,에이틴,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,최고의 치킨,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,왼손잡이 아내,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,왕이 된 남자,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,악귀,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,아씨두리안,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,가슴이 뛴다,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
393,기적의 형제,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 장르 구분 원본

In [29]:
# 원본
# Motion Picture Association의 장르 분류 체계에 따라 장르들을 묶음
genre_groups = {
    '액션': ['액션', '스포츠', '전쟁'],
    '코미디': ['코미디', '로맨틱코미디', '로코', '로맨틱 코미디', '로맨틱 코미디 드라마',
                '코믹', '블랙 코미디', '코믹 미스터리 사극 드라마'],
    '드라마': ['드라마', '멜로', '로맨스', '로맨스 드라마', '로맨스드라마', '로맨틱드라마',
                '멜로 로맨스 코미디', '멜로멜로', '멜로 로맨스'],
    '스릴러': ['스릴러', '범죄', '법률', '범죄물', '법정', '블록버스터', '블랙코미디',
                '사이언스 액션 히어로', '서스펜스', '서스펜스추리', '피카레스크'],
    '공포': ['공포', '호러', '금융'],
    '판타지': ['판타지', '시대극', '판타지 드라마', '판타지로코 드라마'],
    '가족': ['가족', '어드벤처', '첩보', '뮤지컬'],
    '미스터리': ['미스터리', '미스터리 멜로', '미스터리 스릴러', '미스터리 수사물'],
    '전쟁': ['전쟁', '사극'],
    'SF': ['SF', '엑소시즘', '타임 크로싱', '프라이빗 오피스 멜로', '하드보일드', '정치',
                '정치 스릴러', '전쟁 스릴러', '슬래셔 스릴러']
}

### 장르 구분 수정본 (정성오)
출처: https://ko.wikipedia.org/wiki/%EB%B6%84%EB%A5%98:%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EC%9E%A5%EB%A5%B4%EB%B3%84_%ED%85%94%EB%A0%88%EB%B9%84%EC%A0%84_%EB%93%9C%EB%9D%BC%EB%A7%88

In [ ]:
# 수정본

# SF, 가족, 로맨스, 미스터리, 스릴러(범죄, 느와르 관련)
# 액션, 역사, 추리, 코미디, 판타지, 휴먼

genre_groups = {
    '액션': ['액션', '스포츠', '전쟁'],
    '코미디': ['코미디', '로맨틱코미디', '로코', '로맨틱 코미디', '로맨틱 코미디 드라마',
                '코믹', '블랙 코미디', '코믹 미스터리 사극 드라마'],
    '드라마': ['드라마', '멜로', '로맨스', '로맨스 드라마', '로맨스드라마', '로맨틱드라마',
                '멜로 로맨스 코미디', '멜로멜로', '멜로 로맨스'],
    '스릴러': ['스릴러', '범죄', '법률', '범죄물', '법정', '블록버스터', '블랙코미디',
                '사이언스 액션 히어로', '서스펜스', '서스펜스추리', '피카레스크'],
    '공포': ['공포', '호러', '금융'],
    '판타지': ['판타지', '시대극', '판타지 드라마', '판타지로코 드라마'],
    '가족': ['가족', '어드벤처', '첩보', '뮤지컬'],
    '미스터리': ['미스터리', '미스터리 멜로', '미스터리 스릴러', '미스터리 수사물'],
    '전쟁': ['전쟁', '사극'],
    'SF': ['SF', '엑소시즘', '타임 크로싱', '프라이빗 오피스 멜로', '하드보일드', '정치',
                '정치 스릴러', '전쟁 스릴러', '슬래셔 스릴러']
}

In [43]:
# genre_groups 딕셔너리에 정의된 각 그룹에 속하는 열들을 찾아서 grouped_genres에 저장
grouped_genres = {}
for group, genres in genre_groups.items():
    grouped_genres[group] = [genre for genre in meta.columns if any(g in genre for g in genres)]

In [44]:
#grouped_genres 딕셔너리에 저장된 장르 그룹들과
#그에 해당하는 열들을 사용하여 새로운 데이터프레임 만들
grouped_df = pd.DataFrame()
for group, genres in grouped_genres.items():
    grouped_df[group] = meta[genres].sum(axis=1)

In [46]:
grouped_df

     액션  코미디  드라마  스릴러  공포  판타지  가족  미스터리  전쟁  SF
0     0    0    2    0   0    0   0     0   0   0
1     0    0    1    0   0    0   0     0   0   0
2     0    0    1    0   0    0   0     0   0   0
3     0    0    1    1   0    0   0     0   0   0
4     0    0    0    0   0    0   0     0   1   0
..   ..  ...  ...  ...  ..  ...  ..   ...  ..  ..
389   0    0    0    2   0    0   0     0   0   0
390   0    0    0    1   0    1   0     1   0   0
391   0    0    2    0   0    0   0     0   0   1
392   0    1    1    0   1    0   0     0   0   0
393   0    0    1    0   0    0   0     0   0   0

[394 rows x 10 columns]

In [67]:
#작품명과 기타 데이터 살리기
sliced_meta = meta.iloc[:, :5]
sliced_meta

,작품명,장르,방송사,전체회차,출연자
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']"
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']"
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']"
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']"
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']"
...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,12,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']"
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,12,"['김태리', ' 오정세', ' 홍경']"
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",16,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'..."
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,16,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']"
393,기적의 형제,['드라마'],JTBC,16,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']"

In [68]:
merged_df = pd.concat([sliced_meta, grouped_df], axis=1)
merged_df

,작품명,장르,방송사,전체회차,출연자,액션,코미디,드라마,스릴러,공포,판타지,가족,미스터리,전쟁,SF
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",0,0,2,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']",0,0,1,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",0,0,1,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",0,0,1,1,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,12,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']",0,0,0,2,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,12,"['김태리', ' 오정세', ' 홍경']",0,0,0,1,0,1,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",16,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'...",0,0,2,0,0,0,0,0,0,1
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,16,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']",0,1,1,0,1,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,16,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']",0,0,1,0,0,0,0,0,0,0

In [69]:
#각 셀의 원핫인코딩을 살리기 위해 2이상인 것들은 1로 대체함
def replace(x):
    try:
        numeric = pd.to_numeric(x)
    except:
        numeric = float('nan')

    if pd.notnull(numeric) and numeric >= 2:
        return 1
    else:
        return x

In [70]:
merged_df = merged_df.applymap(replace)
merged_df

,작품명,장르,방송사,전체회차,출연자,액션,코미디,드라마,스릴러,공포,판타지,가족,미스터리,전쟁,SF
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",1,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",0,0,1,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",1,"['박선호', ' 김소혜', ' 주우재 ']",0,0,1,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,1,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",0,0,1,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,1,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",0,0,1,1,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,1,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,1,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']",0,0,0,1,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,1,"['김태리', ' 오정세', ' 홍경']",0,0,0,1,0,1,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",1,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'...",0,0,1,0,0,0,0,0,0,1
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,1,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']",0,1,1,0,1,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,1,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']",0,0,1,0,0,0,0,0,0,0

In [74]:
merged_df.to_csv("meta_장르병합.csv", index=False, encoding='cp949')