### Week 2 Assignment

In [1]:
#Drive mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
PATH = '/content/drive/MyDrive/23-2_DSL/EDA' # Dataset Directory Path 지정

In [4]:
names = ['계량경제학(1)','계약및조직이론'] # Dataset Directory 내 강의명 제시

### Add Column Index

In [5]:
for name in names:
    for file in os.listdir(os.path.join(PATH, name)):
        file_csv = file.split('.')[0] + '.csv'
        if file.startswith('202'):
            with open(os.path.join(PATH, name, file), "r") as file_name:
                first_line = file_name.readline()
                if first_line[0] == '1' or first_line[0] == '0':
                    DF = pd.read_csv(os.path.join(PATH, name, file), delimiter = '\t', header = None)
                    DF.columns = ["순위", "마일리지", "특수교육대상자(장애학생)여부", "전공자/복수전공자(전공자정원포함여부)", "신청과목수", "졸업신청", "초수강여부", "총이수학점비율", "직전학기이수학점비율", "학년", "수강여부", "비고"]
                    DF.to_csv(os.path.join(PATH, name, file_csv), index = False)


        os.remove(os.path.join(PATH, name, file))
        print(file, 'is switched to csv format!')

2023_1_대면_정진욱_계량경제학(1).txt is switched to csv format!
2023_1_블렌디드_김태환_계량경제학(1).txt is switched to csv format!
2022_2_대면_정진욱_계량경제학(1).txt is switched to csv format!
2022_2_블렌디드_조진서_계량경제학(1).txt is switched to csv format!
2022_1_비대면_유병삼_계량경제학(1).txt is switched to csv format!
2022_1_대면_정진욱_계량경제학(1).txt is switched to csv format!
2022_1_비대면_김태환_계량경제학(1).txt is switched to csv format!
2021_2_비대면_조진서_계량경제학(1).txt is switched to csv format!
2021_1_블렌디드_유병삼_계량경제학(1).txt is switched to csv format!
2021_1_비대면_김태환_계량경제학(1).txt is switched to csv format!
2020_2_비대면_정진욱_계량경제학(1).txt is switched to csv format!
2020_2_비대면_이진현_계량경제학(1).txt is switched to csv format!
2023_1_블렌디드_김상현_계약및조직이론.txt is switched to csv format!
2022_2_블렌디드_김상현_계약및조직이론.txt is switched to csv format!
2022_1_비대면_김상현_계약및조직이론.txt is switched to csv format!
2021_2_비대면_김상현_계약및조직이론.txt is switched to csv format!
2021_1_비대면_김상현_계약및조직이론.txt is switched to csv format!
2020_2_비대면_김상현_계약및조직이론.txt is switched to csv format!

In [6]:
# 예시 파일
pd.read_csv('/content/drive/MyDrive/23-2_DSL/EDA/계량경제학(1)/2022_1_대면_정진욱_계량경제학(1).csv', delimiter = ',')

,순위,마일리지,특수교육대상자(장애학생)여부,전공자/복수전공자(전공자정원포함여부),신청과목수,졸업신청,초수강여부,총이수학점비율,직전학기이수학점비율,학년,수강여부,비고
0,1,12,N,Y(Y),6,Y,Y,1.000,0.833,4,Y,NaN
1,2,12,N,Y(N),6,Y,Y,0.993,0.947,4,Y,NaN
2,3,12,N,Y(N),6,Y,Y,0.963,0.789,4,Y,NaN
3,4,12,N,Y(N),6,Y,Y,0.921,0.667,4,Y,NaN
4,5,12,N,Y(N),6,Y,Y,0.844,0.632,4,Y,NaN
5,6,12,N,Y(N),6,N,Y,0.886,1.000,4,Y,NaN
6,7,12,N,Y(Y),6,N,Y,0.849,0.722,4,Y,NaN
7,8,12,N,Y(Y),6,N,Y,0.841,1.000,4,Y,NaN
8,9,12,N,Y(N),6,N,Y,0.833,1.000,3,Y,NaN
9,10,12,N,Y(N),6,N,Y,0.826,0.947,4,Y,NaN
10,11,12,N,Y(Y),6,N,Y,0.794,1.000,4,Y,NaN
11,12,12,N,Y(Y),6,N,Y,0.794,0.167,4,Y,NaN
12,13,12,N,Y(Y),6,N,Y,0.770,1.000,3,Y,NaN
13,14,12,N,Y(Y),6,N,Y,0.770,0.861,4,Y,NaN
14,15,12,N,Y(N),6,N,Y,0.741,0.816,4,Y,NaN
15,16,12,N,Y(Y),6,N,Y,0.730,0.833,3,Y,NaN
16,17,12,N,Y(Y),6,N,Y,0.730,0.833,3,Y,NaN
17,18,12,N,Y(Y),6,N,Y,0.687,1.000,3,Y,NaN
18,19,12,N,Y(Y),6,N,Y,0.687,1.000,3,Y,NaN
19,20,12,N,Y(Y),6,N,Y,0.675,1.000,3,Y,NaN
20,21,12,N,Y(Y),6,N,Y,0.675,1.000,3,NaN,NaN
21,22,12,N,Y(Y),6,N,Y,0.611,0.861,3,NaN,NaN
22,23,12,N,Y(Y),6,N,Y,0.571,1.000,3,NaN,NaN
23,24,12,N,Y(Y),6,N,Y,0.563,0.861,3,NaN,NaN
24,25,12,N,Y(Y),6,N,Y,0.532,0.750,3,NaN,NaN
25,26,12,N,Y(Y),6,N,Y,0.500,0.875,3,NaN,NaN
26,27,12,N,Y(Y),5,N,Y,0.448,0.917,2,Y,NaN
27,28,12,N,Y(Y),3,N,Y,0.881,0.833,4,Y,NaN
28,29,12,N,N(N),6,Y,Y,0.976,0.611,4,NaN,NaN
29,30,10,N,Y(Y),6,N,Y,0.690,0.778,3,NaN,NaN
30,31,10,N,Y(Y),6,N,Y,0.464,0.861,2,Y,NaN
31,32,6,N,Y(Y),6,N,Y,0.849,0.833,4,NaN,NaN
32,33,1,N,Y(N),6,Y,Y,1.000,1.000,4,NaN,NaN
33,34,1,N,Y(Y),6,Y,Y,1.000,1.000,4,NaN,NaN
34,35,1,N,N(N),6,Y,Y,0.904,1.000,4,NaN,NaN

In [7]:
for name in names:
    for file in os.listdir(os.path.join(PATH, name)):
        if file.startswith('202'):
            DF = pd.read_csv(os.path.join(PATH, name, file), delimiter = ',')

            if DF['특수교육대상자(장애학생)여부'][0] == 'Y' or DF['특수교육대상자(장애학생)여부'][0] == 'N':
                DF['특수교육대상자(장애학생)여부'] = DF['특수교육대상자(장애학생)여부'].fillna('N').map({'N' : 0, 'Y' : 1}).astype(int)

            if DF['전공자/복수전공자(전공자정원포함여부)'][0] != 1 and DF['전공자/복수전공자(전공자정원포함여부)'][0] != 2 and DF['전공자/복수전공자(전공자정원포함여부)'][0] != 3 and DF['전공자/복수전공자(전공자정원포함여부)'][0] != 4:
                DF['전공자/복수전공자(전공자정원포함여부)'] = DF['전공자/복수전공자(전공자정원포함여부)'].fillna('N(N)').map({'N(N)' : 1, 'N(Y)' : 2, 'Y(N)' : 3, 'Y(Y)' : 4}).astype(int)

            if DF['졸업신청'][0] != 0 and DF['졸업신청'][0] != 1:
                DF['졸업신청'] = DF['졸업신청'].fillna('N').map({'N' : 0, 'Y' : 1}).astype(int)

            if DF['초수강여부'][0] != 0 and DF['초수강여부'][0] != 1:
                DF['초수강여부'] = DF['초수강여부'].fillna('N').map({'N' : 0, 'Y' : 1}).astype(int)

            if DF['수강여부'][0] != 0 and DF['수강여부'][0] != 1:
                DF['수강여부'] = DF['수강여부'].fillna('N').map({'N' : 0, 'Y' : 1}).astype(int)
            DF.to_csv(os.path.join(PATH, name, file), index = False)

            print(file, 'is updated !')

2023_1_대면_정진욱_계량경제학(1).csv is updated !
2023_1_블렌디드_김태환_계량경제학(1).csv is updated !
2022_2_대면_정진욱_계량경제학(1).csv is updated !
2022_2_블렌디드_조진서_계량경제학(1).csv is updated !
2022_1_비대면_유병삼_계량경제학(1).csv is updated !
2022_1_대면_정진욱_계량경제학(1).csv is updated !
2022_1_비대면_김태환_계량경제학(1).csv is updated !
2021_2_비대면_조진서_계량경제학(1).csv is updated !
2021_1_블렌디드_유병삼_계량경제학(1).csv is updated !
2021_1_비대면_김태환_계량경제학(1).csv is updated !
2020_2_비대면_정진욱_계량경제학(1).csv is updated !
2020_2_비대면_이진현_계량경제학(1).csv is updated !
2023_1_블렌디드_김상현_계약및조직이론.csv is updated !
2022_2_블렌디드_김상현_계약및조직이론.csv is updated !
2022_1_비대면_김상현_계약및조직이론.csv is updated !
2021_2_비대면_김상현_계약및조직이론.csv is updated !
2021_1_비대면_김상현_계약및조직이론.csv is updated !
2020_2_비대면_김상현_계약및조직이론.csv is updated !

In [8]:
# 예시 파일
pd.read_csv('/content/drive/MyDrive/23-2_DSL/EDA/계량경제학(1)/2022_1_대면_정진욱_계량경제학(1).csv', delimiter = ',')

,순위,마일리지,특수교육대상자(장애학생)여부,전공자/복수전공자(전공자정원포함여부),신청과목수,졸업신청,초수강여부,총이수학점비율,직전학기이수학점비율,학년,수강여부,비고
0,1,12,0,4,6,1,1,1.000,0.833,4,1,NaN
1,2,12,0,3,6,1,1,0.993,0.947,4,1,NaN
2,3,12,0,3,6,1,1,0.963,0.789,4,1,NaN
3,4,12,0,3,6,1,1,0.921,0.667,4,1,NaN
4,5,12,0,3,6,1,1,0.844,0.632,4,1,NaN
5,6,12,0,3,6,0,1,0.886,1.000,4,1,NaN
6,7,12,0,4,6,0,1,0.849,0.722,4,1,NaN
7,8,12,0,4,6,0,1,0.841,1.000,4,1,NaN
8,9,12,0,3,6,0,1,0.833,1.000,3,1,NaN
9,10,12,0,3,6,0,1,0.826,0.947,4,1,NaN
10,11,12,0,4,6,0,1,0.794,1.000,4,1,NaN
11,12,12,0,4,6,0,1,0.794,0.167,4,1,NaN
12,13,12,0,4,6,0,1,0.770,1.000,3,1,NaN
13,14,12,0,4,6,0,1,0.770,0.861,4,1,NaN
14,15,12,0,3,6,0,1,0.741,0.816,4,1,NaN
15,16,12,0,4,6,0,1,0.730,0.833,3,1,NaN
16,17,12,0,4,6,0,1,0.730,0.833,3,1,NaN
17,18,12,0,4,6,0,1,0.687,1.000,3,1,NaN
18,19,12,0,4,6,0,1,0.687,1.000,3,1,NaN
19,20,12,0,4,6,0,1,0.675,1.000,3,1,NaN
20,21,12,0,4,6,0,1,0.675,1.000,3,0,NaN
21,22,12,0,4,6,0,1,0.611,0.861,3,0,NaN
22,23,12,0,4,6,0,1,0.571,1.000,3,0,NaN
23,24,12,0,4,6,0,1,0.563,0.861,3,0,NaN
24,25,12,0,4,6,0,1,0.532,0.750,3,0,NaN
25,26,12,0,4,6,0,1,0.500,0.875,3,0,NaN
26,27,12,0,4,5,0,1,0.448,0.917,2,1,NaN
27,28,12,0,4,3,0,1,0.881,0.833,4,1,NaN
28,29,12,0,1,6,1,1,0.976,0.611,4,0,NaN
29,30,10,0,4,6,0,1,0.690,0.778,3,0,NaN
30,31,10,0,4,6,0,1,0.464,0.861,2,1,NaN
31,32,6,0,4,6,0,1,0.849,0.833,4,0,NaN
32,33,1,0,3,6,1,1,1.000,1.000,4,0,NaN
33,34,1,0,4,6,1,1,1.000,1.000,4,0,NaN
34,35,1,0,1,6,1,1,0.904,1.000,4,0,NaN

In [9]:
for name in names:
    for file in os.listdir(os.path.join(PATH, name)):
        if file.startswith('202'):
            DF = pd.read_csv(os.path.join(PATH, name, file), delimiter = ',')
            DF = DF.iloc[:, 1:-1] #순위와 비고를 한번에 제거할 수 있는 column index 범위를 찾아보세요!
            DF.to_csv(os.path.join(PATH, name, file), index = False)

In [10]:
# 예시 파일
pd.read_csv('/content/drive/MyDrive/23-2_DSL/EDA/계량경제학(1)/2022_1_대면_정진욱_계량경제학(1).csv', delimiter = ',')

,마일리지,특수교육대상자(장애학생)여부,전공자/복수전공자(전공자정원포함여부),신청과목수,졸업신청,초수강여부,총이수학점비율,직전학기이수학점비율,학년,수강여부
0,12,0,4,6,1,1,1.000,0.833,4,1
1,12,0,3,6,1,1,0.993,0.947,4,1
2,12,0,3,6,1,1,0.963,0.789,4,1
3,12,0,3,6,1,1,0.921,0.667,4,1
4,12,0,3,6,1,1,0.844,0.632,4,1
5,12,0,3,6,0,1,0.886,1.000,4,1
6,12,0,4,6,0,1,0.849,0.722,4,1
7,12,0,4,6,0,1,0.841,1.000,4,1
8,12,0,3,6,0,1,0.833,1.000,3,1
9,12,0,3,6,0,1,0.826,0.947,4,1
10,12,0,4,6,0,1,0.794,1.000,4,1
11,12,0,4,6,0,1,0.794,0.167,4,1
12,12,0,4,6,0,1,0.770,1.000,3,1
13,12,0,4,6,0,1,0.770,0.861,4,1
14,12,0,3,6,0,1,0.741,0.816,4,1
15,12,0,4,6,0,1,0.730,0.833,3,1
16,12,0,4,6,0,1,0.730,0.833,3,1
17,12,0,4,6,0,1,0.687,1.000,3,1
18,12,0,4,6,0,1,0.687,1.000,3,1
19,12,0,4,6,0,1,0.675,1.000,3,1
20,12,0,4,6,0,1,0.675,1.000,3,0
21,12,0,4,6,0,1,0.611,0.861,3,0
22,12,0,4,6,0,1,0.571,1.000,3,0
23,12,0,4,6,0,1,0.563,0.861,3,0
24,12,0,4,6,0,1,0.532,0.750,3,0
25,12,0,4,6,0,1,0.500,0.875,3,0
26,12,0,4,5,0,1,0.448,0.917,2,1
27,12,0,4,3,0,1,0.881,0.833,4,1
28,12,0,1,6,1,1,0.976,0.611,4,0
29,10,0,4,6,0,1,0.690,0.778,3,0
30,10,0,4,6,0,1,0.464,0.861,2,1
31,6,0,4,6,0,1,0.849,0.833,4,0
32,1,0,3,6,1,1,1.000,1.000,4,0
33,1,0,4,6,1,1,1.000,1.000,4,0
34,1,0,1,6,1,1,0.904,1.000,4,0